### ISSUE TITLE
If folder name contains Exclamation Sign (!), live-server is not detecting the changes of file.

### ISSUE THREAD

**Issue by ritwickdey** [tapio/live-server#212] opened 2017-09-12 12:21 UTC
## Issue description
If folder name contains Exclamation Sign (!) *[e.g. c:\folder!name\subfolder]*, live-server is not detecting the changes of file if sever starts from 'subfolder'.

I've checked the code. Actually, *chokidar* library is detecting the changes of file in this case.

We have to use `disableGlobbing: true`  here,
https://github.com/tapio/live-server/blob/cf32d6342bfbba94bd0d4b24e09838fd2d2caba7/index.js#L356-L359 

Chokidar Issue : https://github.com/paulmillr/chokidar/issues/630

### Software details
* OS: Windows & Linux

**Comment by tapio** [comment] 2017-10-09 20:14
I think this is a duplicate of #193 and is a bit more complex issue since globbing may be desirable.

**Closed by tapio** 2017-10-09 20:14 UTC

**Comment by ritwickdey** [comment] 2017-10-09 20:20
But, in #193 they are describe about folder staring with dot(.). ... By default, I've checked the code, live-server ignores the folder which is starting with dot(.) as most the the IDE/Editor config/cache folder starts with dot.

But this issue is about Exclamation Sign (!). I've submitted the PR with fix. #213

**Comment by bhowley** [comment] 2017-10-15 05:56
Same issue when the path contains parens (IE: "C:\(Code)\Spikes") - live-server doesn't detect the changes. Moving the same project to a different path without parens works.
