### ISSUE TITLE
If folder is hide file, live-server is not detecting the changes of file.

### ISSUE THREAD

**Issue by zhuzhenzhen** [tapio/live-server#216] opened 2017-09-15 02:52 UTC
I used 
const params = {
    port: '8989',
    root: '/docs/test/.raml_html',
    open: true,
  }
  liveServer.start(params)

but live-server is not detecting the changes of file.

**Comment by tapio** [comment] 2017-10-09 20:10
Duplicate of #193, the dot in the file path makes the change detection fail.

**Closed by tapio** 2017-10-09 20:10 UTC
