### ISSUE TITLE
On-the-fly css refresh not working

### ISSUE THREAD

**Issue by rahmatawaludin** [tapio/live-server#5] opened 2014-12-20 12:22 UTC
Thanks @tapio , you have made a great library.

I have html like this:

````
<!DOCTYPE html>
<html>
<head>
	<title>Belajar</title>
	<link rel="stylesheet" href="style.css">
</head>
<body>
	<strong>Helos</strong>
</body>
</html>
````

And `style.css`, like this:

````
strong {
	color: pink;
}
````

HTML is automatically reload when there is a change, but css is not automatically changed when there is a change is CSS. My terminal say `CSS Change detected`. What should I do??

Update: on-the-fly css refresh is works when I hover over browser (I'm using Chrome 39.0.2171.95 (64-bit). If my cursor stay in my text editor (sublime), the change (CSS) won't show up in browser.

Here is my generated html:

````

<script>
	// Code injected by live-server
	(function() {
		function refreshCSS() {
			var sheets = document.getElementsByTagName("link");
			for (var i = 0; i < sheets.length; ++i) {
				var elem = sheets[i];
				var rel = elem.rel;
				if (elem.href && typeof rel != "string" || rel.length == 0 || rel.toLowerCase() == "stylesheet") {
					var url = elem.href.replace(/(&|\?)_cacheOverride=d+/, '');
					elem.href = url + (url.indexOf('?') >= 0 ? '&' : '?') + '_cacheOverride=' + (new Date().valueOf());
				}
			}
		}
		protocol = window.location.protocol === 'http:' ? 'ws://' : 'wss://'; 
		address = protocol + window.location.host + window.location.pathname + '/ws'; 
		socket = new WebSocket(address); 
		socket.onmessage = function(msg) {
			if (msg.data == 'reload') window.location.reload()
			else if (msg.data == 'refreshcss') refreshCSS();
		}; 
		console.log('Live reload enabled.'); 
	})();
</script>
<!DOCTYPE html>
<html>
<head>
	<title>Belajar</title>
	<link rel="stylesheet" href="style.css">
</head>
<body>
	<strong>Helos</strong>
</body>
</html>
````
Thanks.

**Comment by simplesmiler** [comment] 2015-01-06 16:34
May this be related to #6?

**Comment by tapio** [comment] 2015-01-07 18:05
@simplesmiler Nice guess, but I tested it by manually putting the code inside `<body>` and disabled the injecting from live-server. However, there was no improvement.

Interestingly, I can trigger the bug with @rahmatawaludin's minimal test case code, but when I tried with a couple of my own, larger codebases it was working fine - no need to mouse hover the window. I tried to add some stuff to the minimal html/css in order to find what might "fix" it, but no luck so far. :/

**Comment by simplesmiler** [comment] 2015-01-18 21:21
Chrome is being either a smartypants or a dummy.
One dirty workaround I found is to apply an infinite but pointless animation:
```css
@-webkit-keyframes livefix { from { opacity: 1; } to { opacity: 1; } }
html { -webkit-animation: livefix infinite 1s; }
```

**Comment by Mario-M** [comment] 2015-03-26 23:03
Another confirmed case here. Pointless animation is effective as a workaround for the time being.

**Comment by 1j01** [comment] 2015-05-30 01:49
:+1: Perhaps the server could inject this hack.

**Comment by harrytruong** [comment] 2015-07-23 21:37
Hey, I've also confirmed this issue. I disagree with the pointless animation workaround, and I'm submitting a PR with a cleaner solution. 

Chrome doesn't detect the `href` change in the `<link />` elements, but we can force detection by detaching `<link />` from the DOM, updating the `href`, and then re-attaching. No need for any crazy css.

**Comment by harrytruong** [comment] 2015-07-24 14:33
@rahmatawaludin @simplesmiler @Mario-M @1j01 

The PR has been merged, and the fix for chrome should be in now. Let us know if it doesn't work?

**Comment by simplesmiler** [comment] 2015-07-24 14:45
@harrytruong will test today or tomorrow.

**Comment by simplesmiler** [comment] 2015-07-26 02:11
@harrytruong if I checkout to the 5cbb17fd4211e267f00cd0b13ddb8c9ad15bbd5c css seems to be refreshing just fine.
Win7 x86_64, Chrome 44.0.2403.107 m, node v0.12.5.

**Comment by harrytruong** [comment] 2015-07-26 14:25
Great, thanks. @tapio I think we can close this.

**Closed** 2015-07-26 16:30 UTC

**Comment by joerick** [comment] 2018-04-28 15:48
If anyone else is running into problems with this, I was getting an error in console
![image](https://user-images.githubusercontent.com/1244307/39398242-ef103afc-4b02-11e8-9599-b5960877ab98.png)
> Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

The reason is that my CSS \<link\> tag was not in \<head\>, but in \<body\>. Moving them into \<head\> (as is technically correct) solved the problem.

**Comment by thejoecode** [comment] 2018-09-12 12:11
@joerick I was running into the same issue. Thank you for the fix of moving the link tag to the head. Would be great if this could be detected or worked around in the future though.

**Comment by stevenspinoza** [comment] 2019-01-21 22:19
Same issue as @joerick , but after looking at the DevTools, I had a Chrome extension named Night Mode Pro installed, which **added two other \<link\> files at the top of the file**. Due to to **not being inside the \<head\>** element, it popped this error, so I had to disable the extension and voila! Exception Solved!
