### ISSUE TITLE
Angular partials not loading.

### ISSUE THREAD

**Issue by Alchemist84** [tapio/live-server#30] opened 2015-03-28 18:27 UTC
Trying to load angular partials through the ng-include directive and the app hangs by saying that the resource could not be located (through the console) even though i am calling the partial the right way by using single quotes etc.

**Comment by tapio** [comment] 2015-03-31 18:56
This is probably a duplicate of #27, which should be fixed by the fresh 0.7.1. Feel free to reopen if the issue persists.

**Closed by tapio** 2015-03-31 18:56 UTC
